import { sbbInformationArray } from 'src/app/modelData';

/**
 *
 */
export function getSingleTestData(): sbbInformationArray {
    return [
        {
            lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
            geopos: {
                lon: 8.54848908844946,
                lat: 47.3666097667102
            },
            numbershort: 3003,
            uiccountrycode: 85,
            sloid: 'ch:1:sloid:3003',
            number: 8503003,
            validfrom: '2021-04-01',
            validto: '2099-12-31',
            designationofficial: 'Zürich Stadelhofen',
            designationlong: null,
            abbreviation: 'ZSTH',
            operatingpoint: 'true',
            operatingpointwithtimetable: 'true',
            stoppoint: 'true',
            stoppointtype: 'ORDERLY',
            freightservicepoint: 'false',
            trafficpoint: 'true',
            borderpoint: 'false',
            hasgeolocation: 'true',
            isocountrycode: 'CH',
            cantonname: 'Zürich',
            cantonfsonumber: '1',
            cantonabbreviation: 'ZH',
            districtname: 'Zürich',
            districtfsonumber: '112',
            municipalityname: 'Zürich',
            fsonumber: '261',
            localityname: 'Zürich',
            operatingpointtype: null,
            operatingpointtechnicaltimetabletype: null,
            meansoftransport: 'TRAIN',
            categories: null,
            operatingpointtrafficpointtype: null,
            operatingpointroutenetwork: 'true',
            operatingpointkilometer: 'true',
            operatingpointkilometermasternumber: '8503003',
            sortcodeofdestinationstation: null,
            businessorganisation: 'ch:1:sboid:100001',
            businessorganisationnumber: 11,
            businessorganisationabbreviationde: 'SBB',
            businessorganisationabbreviationfr: 'CFF',
            businessorganisationdescriptionde: 'Schweizerische Bundesbahnen SBB',
            businessorganisationdescriptionfr: 'Chemins de fer fédéraux suisses CFF',
            fotcomment: null,
            height: 409.7,
            creationdate: '2017-11-09T21:09:02+00:00',
            editiondate: '2022-02-23T14:46:56+00:00'
        }
    ];
}

/**
 *
 */
// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function getMultipleData() {
    return {
        Payload: [
            {
                lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
                geopos: {
                    lon: 9.20978353611554,
                    lat: 47.6376192399992
                },
                numbershort: 73411,
                uiccountrycode: 85,
                sloid: 'ch:1:sloid:73411',
                number: 8573411,
                validfrom: '2022-07-26',
                validto: '2099-12-31',
                designationofficial: 'Bottighofen, Turnhalle',
                designationlong: null,
                abbreviation: null,
                operatingpoint: 'true',
                operatingpointwithtimetable: 'true',
                stoppoint: 'true',
                stoppointtype: 'ORDERLY',
                freightservicepoint: 'false',
                trafficpoint: 'true',
                borderpoint: 'false',
                hasgeolocation: 'true',
                isocountrycode: 'CH',
                cantonname: 'Thurgau',
                cantonfsonumber: '20',
                cantonabbreviation: 'TG',
                districtname: 'Kreuzlingen',
                districtfsonumber: '2013',
                municipalityname: 'Bottighofen',
                fsonumber: '4643',
                localityname: 'Bottighofen',
                operatingpointtype: null,
                operatingpointtechnicaltimetabletype: null,
                meansoftransport: 'BUS',
                categories: null,
                operatingpointtrafficpointtype: null,
                operatingpointroutenetwork: 'false',
                operatingpointkilometer: 'false',
                operatingpointkilometermasternumber: null,
                sortcodeofdestinationstation: null,
                businessorganisation: 'ch:1:sboid:100602',
                businessorganisationnumber: 801,
                businessorganisationabbreviationde: 'PAG',
                businessorganisationabbreviationfr: 'PAG',
                businessorganisationdescriptionde: 'PostAuto AG',
                businessorganisationdescriptionfr: 'CarPostal SA',
                fotcomment: null,
                height: 414,
                creationdate: '2017-11-09T11:53:05+00:00',
                editiondate: '2022-07-29T11:30:52+00:00'
            },
            {
                lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
                geopos: {
                    lon: 9.21215816164162,
                    lat: 47.6389773093497
                },
                numbershort: 10468,
                uiccountrycode: 85,
                sloid: 'ch:1:sloid:10468',
                number: 8510468,
                validfrom: '2023-11-15',
                validto: '2099-12-31',
                designationofficial: 'Bottighofen, Hauptstrasse',
                designationlong: null,
                abbreviation: null,
                operatingpoint: 'true',
                operatingpointwithtimetable: 'true',
                stoppoint: 'true',
                stoppointtype: 'ON_REQUEST',
                freightservicepoint: 'false',
                trafficpoint: 'true',
                borderpoint: 'false',
                hasgeolocation: 'true',
                isocountrycode: 'CH',
                cantonname: 'Thurgau',
                cantonfsonumber: '20',
                cantonabbreviation: 'TG',
                districtname: 'Kreuzlingen',
                districtfsonumber: '2013',
                municipalityname: 'Bottighofen',
                fsonumber: '4643',
                localityname: 'Bottighofen',
                operatingpointtype: null,
                operatingpointtechnicaltimetabletype: null,
                meansoftransport: 'BUS',
                categories: null,
                operatingpointtrafficpointtype: null,
                operatingpointroutenetwork: 'false',
                operatingpointkilometer: 'false',
                operatingpointkilometermasternumber: null,
                sortcodeofdestinationstation: null,
                businessorganisation: 'ch:1:sboid:1100021',
                businessorganisationnumber: 7231,
                businessorganisationabbreviationde: 'SBB-EV',
                businessorganisationabbreviationfr: 'SBB-EV',
                businessorganisationdescriptionde: 'SBB Infrastruktur AG Bahnersatz',
                businessorganisationdescriptionfr: 'SBB Infrastruktur AG Bahnersatz',
                fotcomment: null,
                height: 415.3,
                creationdate: '2022-01-31T13:37:41+00:00',
                editiondate: '2023-11-15T12:48:09+00:00'
            },
            {
                lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
                geopos: {
                    lon: 9.20768567862396,
                    lat: 47.6397652312849
                },
                numbershort: 73410,
                uiccountrycode: 85,
                sloid: 'ch:1:sloid:73410',
                number: 8573410,
                validfrom: '2022-07-26',
                validto: '2099-12-31',
                designationofficial: 'Bottighofen, Post',
                designationlong: null,
                abbreviation: null,
                operatingpoint: 'true',
                operatingpointwithtimetable: 'true',
                stoppoint: 'true',
                stoppointtype: 'ORDERLY',
                freightservicepoint: 'false',
                trafficpoint: 'true',
                borderpoint: 'false',
                hasgeolocation: 'true',
                isocountrycode: 'CH',
                cantonname: 'Thurgau',
                cantonfsonumber: '20',
                cantonabbreviation: 'TG',
                districtname: 'Kreuzlingen',
                districtfsonumber: '2013',
                municipalityname: 'Bottighofen',
                fsonumber: '4643',
                localityname: 'Bottighofen',
                operatingpointtype: null,
                operatingpointtechnicaltimetabletype: null,
                meansoftransport: 'BUS',
                categories: null,
                operatingpointtrafficpointtype: null,
                operatingpointroutenetwork: 'false',
                operatingpointkilometer: 'false',
                operatingpointkilometermasternumber: null,
                sortcodeofdestinationstation: null,
                businessorganisation: 'ch:1:sboid:100602',
                businessorganisationnumber: 801,
                businessorganisationabbreviationde: 'PAG',
                businessorganisationabbreviationfr: 'PAG',
                businessorganisationdescriptionde: 'PostAuto AG',
                businessorganisationdescriptionfr: 'CarPostal SA',
                fotcomment: null,
                height: 406,
                creationdate: '2017-11-09T11:53:05+00:00',
                editiondate: '2022-07-29T11:30:50+00:00'
            },
            {
                lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
                geopos: {
                    lon: 9.21310411429115,
                    lat: 47.6407072444154
                },
                numbershort: 6127,
                uiccountrycode: 85,
                sloid: 'ch:1:sloid:6127',
                number: 8506127,
                validfrom: '2021-04-01',
                validto: '2099-12-31',
                designationofficial: 'Bottighofen',
                designationlong: null,
                abbreviation: 'BOT',
                operatingpoint: 'true',
                operatingpointwithtimetable: 'true',
                stoppoint: 'true',
                stoppointtype: 'ORDERLY',
                freightservicepoint: 'false',
                trafficpoint: 'true',
                borderpoint: 'false',
                hasgeolocation: 'true',
                isocountrycode: 'CH',
                cantonname: 'Thurgau',
                cantonfsonumber: '20',
                cantonabbreviation: 'TG',
                districtname: 'Kreuzlingen',
                districtfsonumber: '2013',
                municipalityname: 'Bottighofen',
                fsonumber: '4643',
                localityname: 'Bottighofen',
                operatingpointtype: null,
                operatingpointtechnicaltimetabletype: null,
                meansoftransport: 'TRAIN',
                categories: null,
                operatingpointtrafficpointtype: null,
                operatingpointroutenetwork: 'true',
                operatingpointkilometer: 'true',
                operatingpointkilometermasternumber: '8506127',
                sortcodeofdestinationstation: null,
                businessorganisation: 'ch:1:sboid:100001',
                businessorganisationnumber: 11,
                businessorganisationabbreviationde: 'SBB',
                businessorganisationabbreviationfr: 'CFF',
                businessorganisationdescriptionde: 'Schweizerische Bundesbahnen SBB',
                businessorganisationdescriptionfr: 'Chemins de fer fédéraux suisses CFF',
                fotcomment: null,
                height: 405.15,
                creationdate: '2017-11-12T08:27:57+00:00',
                editiondate: '2022-02-24T14:37:20+00:00'
            },
            {
                lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
                geopos: {
                    lon: 9.21189834630252,
                    lat: 47.6447385327919
                },
                numbershort: 30720,
                uiccountrycode: 85,
                sloid: 'ch:1:sloid:30720',
                number: 8530720,
                validfrom: '2021-04-01',
                validto: '2099-12-31',
                designationofficial: 'Bottighofen (See)',
                designationlong: null,
                abbreviation: null,
                operatingpoint: 'true',
                operatingpointwithtimetable: 'true',
                stoppoint: 'true',
                stoppointtype: 'ORDERLY',
                freightservicepoint: 'false',
                trafficpoint: 'true',
                borderpoint: 'false',
                hasgeolocation: 'true',
                isocountrycode: 'CH',
                cantonname: 'Thurgau',
                cantonfsonumber: '20',
                cantonabbreviation: 'TG',
                districtname: 'Kreuzlingen',
                districtfsonumber: '2013',
                municipalityname: 'Bottighofen',
                fsonumber: '4643',
                localityname: 'Bottighofen',
                operatingpointtype: null,
                operatingpointtechnicaltimetabletype: null,
                meansoftransport: 'BOAT',
                categories: null,
                operatingpointtrafficpointtype: null,
                operatingpointroutenetwork: 'false',
                operatingpointkilometer: 'false',
                operatingpointkilometermasternumber: null,
                sortcodeofdestinationstation: null,
                businessorganisation: 'ch:1:sboid:100154',
                businessorganisationnumber: 195,
                businessorganisationabbreviationde: 'SBS',
                businessorganisationabbreviationfr: 'SBS',
                businessorganisationdescriptionde: 'Schweizerische Bodensee-Schifffahrt AG',
                businessorganisationdescriptionfr: 'Schweizerische Bodensee-Schifffahrt AG',
                fotcomment: null,
                height: 398,
                creationdate: '2017-11-09T11:53:05+00:00',
                editiondate: '2022-02-24T13:56:26+00:00'
            }
        ]
    };
}
const cityDataMoch: sbbInformationArray = [
    {
        lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
        geopos: {
            lon: 9.20978353611554,
            lat: 47.6376192399992
        },
        numbershort: 73411,
        uiccountrycode: 85,
        sloid: 'ch:1:sloid:73411',
        number: 8573411,
        validfrom: '2022-07-26',
        validto: '2099-12-31',
        designationofficial: 'Bottighofen, Turnhalle',
        designationlong: null,
        abbreviation: null,
        operatingpoint: 'true',
        operatingpointwithtimetable: 'true',
        stoppoint: 'true',
        stoppointtype: 'ORDERLY',
        freightservicepoint: 'false',
        trafficpoint: 'true',
        borderpoint: 'false',
        hasgeolocation: 'true',
        isocountrycode: 'CH',
        cantonname: 'Thurgau',
        cantonfsonumber: '20',
        cantonabbreviation: 'TG',
        districtname: 'Kreuzlingen',
        districtfsonumber: '2013',
        municipalityname: 'Bottighofen',
        fsonumber: '4643',
        localityname: 'Bottighofen',
        operatingpointtype: null,
        operatingpointtechnicaltimetabletype: null,
        meansoftransport: 'BUS',
        categories: null,
        operatingpointtrafficpointtype: null,
        operatingpointroutenetwork: 'false',
        operatingpointkilometer: 'false',
        operatingpointkilometermasternumber: null,
        sortcodeofdestinationstation: null,
        businessorganisation: 'ch:1:sboid:100602',
        businessorganisationnumber: 801,
        businessorganisationabbreviationde: 'PAG',
        businessorganisationabbreviationfr: 'PAG',
        businessorganisationdescriptionde: 'PostAuto AG',
        businessorganisationdescriptionfr: 'CarPostal SA',
        fotcomment: null,
        height: 414,
        creationdate: '2017-11-09T11:53:05+00:00',
        editiondate: '2022-07-29T11:30:52+00:00'
    },
    {
        lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
        geopos: {
            lon: 9.21215816164162,
            lat: 47.6389773093497
        },
        numbershort: 10468,
        uiccountrycode: 85,
        sloid: 'ch:1:sloid:10468',
        number: 8510468,
        validfrom: '2023-11-15',
        validto: '2099-12-31',
        designationofficial: 'Bottighofen, Hauptstrasse',
        designationlong: null,
        abbreviation: null,
        operatingpoint: 'true',
        operatingpointwithtimetable: 'true',
        stoppoint: 'true',
        stoppointtype: 'ON_REQUEST',
        freightservicepoint: 'false',
        trafficpoint: 'true',
        borderpoint: 'false',
        hasgeolocation: 'true',
        isocountrycode: 'CH',
        cantonname: 'Thurgau',
        cantonfsonumber: '20',
        cantonabbreviation: 'TG',
        districtname: 'Kreuzlingen',
        districtfsonumber: '2013',
        municipalityname: 'Bottighofen',
        fsonumber: '4643',
        localityname: 'Bottighofen',
        operatingpointtype: null,
        operatingpointtechnicaltimetabletype: null,
        meansoftransport: 'BUS',
        categories: null,
        operatingpointtrafficpointtype: null,
        operatingpointroutenetwork: 'false',
        operatingpointkilometer: 'false',
        operatingpointkilometermasternumber: null,
        sortcodeofdestinationstation: null,
        businessorganisation: 'ch:1:sboid:1100021',
        businessorganisationnumber: 7231,
        businessorganisationabbreviationde: 'SBB-EV',
        businessorganisationabbreviationfr: 'SBB-EV',
        businessorganisationdescriptionde: 'SBB Infrastruktur AG Bahnersatz',
        businessorganisationdescriptionfr: 'SBB Infrastruktur AG Bahnersatz',
        fotcomment: null,
        height: 415.3,
        creationdate: '2022-01-31T13:37:41+00:00',
        editiondate: '2023-11-15T12:48:09+00:00'
    },
    {
        lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
        geopos: {
            lon: 9.20768567862396,
            lat: 47.6397652312849
        },
        numbershort: 73410,
        uiccountrycode: 85,
        sloid: 'ch:1:sloid:73410',
        number: 8573410,
        validfrom: '2022-07-26',
        validto: '2099-12-31',
        designationofficial: 'Bottighofen, Post',
        designationlong: null,
        abbreviation: null,
        operatingpoint: 'true',
        operatingpointwithtimetable: 'true',
        stoppoint: 'true',
        stoppointtype: 'ORDERLY',
        freightservicepoint: 'false',
        trafficpoint: 'true',
        borderpoint: 'false',
        hasgeolocation: 'true',
        isocountrycode: 'CH',
        cantonname: 'Thurgau',
        cantonfsonumber: '20',
        cantonabbreviation: 'TG',
        districtname: 'Kreuzlingen',
        districtfsonumber: '2013',
        municipalityname: 'Bottighofen',
        fsonumber: '4643',
        localityname: 'Bottighofen',
        operatingpointtype: null,
        operatingpointtechnicaltimetabletype: null,
        meansoftransport: 'BUS',
        categories: null,
        operatingpointtrafficpointtype: null,
        operatingpointroutenetwork: 'false',
        operatingpointkilometer: 'false',
        operatingpointkilometermasternumber: null,
        sortcodeofdestinationstation: null,
        businessorganisation: 'ch:1:sboid:100602',
        businessorganisationnumber: 801,
        businessorganisationabbreviationde: 'PAG',
        businessorganisationabbreviationfr: 'PAG',
        businessorganisationdescriptionde: 'PostAuto AG',
        businessorganisationdescriptionfr: 'CarPostal SA',
        fotcomment: null,
        height: 406,
        creationdate: '2017-11-09T11:53:05+00:00',
        editiondate: '2022-07-29T11:30:50+00:00'
    },
    {
        lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
        geopos: {
            lon: 9.21310411429115,
            lat: 47.6407072444154
        },
        numbershort: 6127,
        uiccountrycode: 85,
        sloid: 'ch:1:sloid:6127',
        number: 8506127,
        validfrom: '2021-04-01',
        validto: '2099-12-31',
        designationofficial: 'Bottighofen',
        designationlong: null,
        abbreviation: 'BOT',
        operatingpoint: 'true',
        operatingpointwithtimetable: 'true',
        stoppoint: 'true',
        stoppointtype: 'ORDERLY',
        freightservicepoint: 'false',
        trafficpoint: 'true',
        borderpoint: 'false',
        hasgeolocation: 'true',
        isocountrycode: 'CH',
        cantonname: 'Thurgau',
        cantonfsonumber: '20',
        cantonabbreviation: 'TG',
        districtname: 'Kreuzlingen',
        districtfsonumber: '2013',
        municipalityname: 'Bottighofen',
        fsonumber: '4643',
        localityname: 'Bottighofen',
        operatingpointtype: null,
        operatingpointtechnicaltimetabletype: null,
        meansoftransport: 'TRAIN',
        categories: null,
        operatingpointtrafficpointtype: null,
        operatingpointroutenetwork: 'true',
        operatingpointkilometer: 'true',
        operatingpointkilometermasternumber: '8506127',
        sortcodeofdestinationstation: null,
        businessorganisation: 'ch:1:sboid:100001',
        businessorganisationnumber: 11,
        businessorganisationabbreviationde: 'SBB',
        businessorganisationabbreviationfr: 'CFF',
        businessorganisationdescriptionde: 'Schweizerische Bundesbahnen SBB',
        businessorganisationdescriptionfr: 'Chemins de fer fédéraux suisses CFF',
        fotcomment: null,
        height: 405.15,
        creationdate: '2017-11-12T08:27:57+00:00',
        editiondate: '2022-02-24T14:37:20+00:00'
    },
    {
        lod: 'http://lod.opentransportdata.swiss/didok/bpuic',
        geopos: {
            lon: 9.21189834630252,
            lat: 47.6447385327919
        },
        numbershort: 30720,
        uiccountrycode: 85,
        sloid: 'ch:1:sloid:30720',
        number: 8530720,
        validfrom: '2021-04-01',
        validto: '2099-12-31',
        designationofficial: 'Bottighofen (See)',
        designationlong: null,
        abbreviation: null,
        operatingpoint: 'true',
        operatingpointwithtimetable: 'true',
        stoppoint: 'true',
        stoppointtype: 'ORDERLY',
        freightservicepoint: 'false',
        trafficpoint: 'true',
        borderpoint: 'false',
        hasgeolocation: 'true',
        isocountrycode: 'CH',
        cantonname: 'Thurgau',
        cantonfsonumber: '20',
        cantonabbreviation: 'TG',
        districtname: 'Kreuzlingen',
        districtfsonumber: '2013',
        municipalityname: 'Bottighofen',
        fsonumber: '4643',
        localityname: 'Bottighofen',
        operatingpointtype: null,
        operatingpointtechnicaltimetabletype: null,
        meansoftransport: 'BOAT',
        categories: null,
        operatingpointtrafficpointtype: null,
        operatingpointroutenetwork: 'false',
        operatingpointkilometer: 'false',
        operatingpointkilometermasternumber: null,
        sortcodeofdestinationstation: null,
        businessorganisation: 'ch:1:sboid:100154',
        businessorganisationnumber: 195,
        businessorganisationabbreviationde: 'SBS',
        businessorganisationabbreviationfr: 'SBS',
        businessorganisationdescriptionde: 'Schweizerische Bodensee-Schifffahrt AG',
        businessorganisationdescriptionfr: 'Schweizerische Bodensee-Schifffahrt AG',
        fotcomment: null,
        height: 398,
        creationdate: '2017-11-09T11:53:05+00:00',
        editiondate: '2022-02-24T13:56:26+00:00'
    }
];
export default { cityDataMoch };
