name: Workflow docker registry and build 

on:
    push:
        branches:
            - main

env:
  REGISTRY_GHCR: ghcr.io
  NAMESPACE_GHCR: yanisb
  IMAGE_NAME: yanis
  USERNAME: ybuelow

jobs:
  build_and_push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
                username: ${{ env.USERNAME }}
                password: ${{ secrets.SECRET_KEY}}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
            push: true
            tags: user/app:latest