name: Workflow docker registry and build

on:
  push:
    branches:
      - main

env:
  REGISTRY_GHCR: ghcr.io
  NAMESPACE_GHCR: yanisb
  IMAGE_NAME: yanis

jobs:
  build_and_push:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Check out the repo
        uses: actions/checkout@v3

      # Set up QEMU for cross-platform builds (optional, if needed)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_GHCR }}  # ghcr.io for GitHub Container Registry
          username: ${{ github.repository_owner }}  # GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.REGISTRY_GHCR }}/${{ env.NAMESPACE_GHCR }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            NODE_ENV=production
